# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_core.ipynb.

# %% auto 0
__all__ = ['say_hello', 'say_goodbye']

# %% ../00_core.ipynb 3
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'

# %% ../00_core.ipynb 4
def say_goodbye(to):
    "Say goodbye to somebody"
    return f'Goodbye {to}!'
